import os 
import subprocess
from google.genai import types

def run_python_file(working_directory, file_name):
    try: 
        working_dir_path = os.path.abspath(working_directory)
        file_path = os.path.abspath(os.path.join(working_directory, file_name))

        if file_path and  not os.path.exists(file_path): 
            return f'Error: File "{file_name}" not found.'

        if file_path.split('.')[-1] != "py": 
            return f'Error: "{file_name}" is not a Python file.'
        
        if not file_path.startswith(working_dir_path): 
            return f'Error: Cannot execute "{file_name}" as it is outside the permitted working directory'
        
        
        results = subprocess.run(
            ["python3", file_name], 
            capture_output= True, 
            text= True, 
            timeout=30,
            cwd=working_dir_path
        )

        output = []

        if results.stdout: 
            output.append("STDOUT:\n" + results.stdout)
        if results.stderr: 
            output.append("STDERR:\n" + results.stderr)
        if results.returncode !=0: 
            output.append(f"Process exited with code {results.returncode}.")
        if not output:
            return "no outpur produced."
        else: 
            return "\n".join(output)

    except Exception as e: 
        return f"Error: {e}"

schema_run_python_file = types.FunctionDeclaration(
    name="run_python_file",
    description="Run the python file and prints the Output.",
    parameters=types.Schema(
        type=types.Type.OBJECT,
        properties={
            "directory": types.Schema(
                type=types.Type.STRING,
                description="The directory to list files from, relative to the working directory. If not provided, lists files in the working directory itself.",
            ),
            "output": types.Schema(
                type=types.Type.STRING,
                description="The output generated by running the python file.",
            ),
        },
    ),
)